perf stat -e \
L1-icache-load-misses,\
icache_16b.ifdata_stall,\
icache_64b.iftag_hit,\
icache_64b.iftag_miss,\
icache_64b.iftag_stall,\
idq.all_dsb_cycles_4_uops,\
idq.all_dsb_cycles_any_uops,\
idq.all_mite_cycles_4_uops,\
idq.all_mite_cycles_any_uops,\
idq.dsb_uops,\
idq.mite_uops,\
idq.ms_uops,\
idq.dsb_cycles,\
idq.mite_cycles,\
idq.ms_cycles,\
idq.ms_dsb_cycles,\
idq.ms_mite_uops,\
idq.ms_switches,\
idq_uops_not_delivered.core,\
idq_uops_not_delivered.cycles_0_uops_deliv.core,\
idq_uops_not_delivered.cycles_le_1_uop_deliv.core,\
idq_uops_not_delivered.cycles_le_2_uop_deliv.core,\
idq_uops_not_delivered.cycles_le_3_uop_deliv.core,\
idq_uops_not_delivered.cycles_fe_was_ok,\
dsb2mite_switches.penalty_cycles,\
frontend_retired.dsb_miss,\
frontend_retired.itlb_miss,\
frontend_retired.l1i_miss,\
frontend_retired.l2_miss,\
frontend_retired.latency_ge_2,\
frontend_retired.latency_ge_4,\
frontend_retired.latency_ge_8,\
frontend_retired.latency_ge_16,\
frontend_retired.latency_ge_32,\
frontend_retired.latency_ge_64,\
frontend_retired.latency_ge_128,\
frontend_retired.latency_ge_256,\
frontend_retired.latency_ge_512,\
frontend_retired.latency_ge_2_bubbles_ge_1,\
frontend_retired.latency_ge_2_bubbles_ge_2,\
frontend_retired.latency_ge_2_bubbles_ge_3,\
frontend_retired.stlb_miss,\
frontend_retired.itlb_miss,\
itlb.itlb_flush,\
itlb_misses.miss_causes_a_walk,\
itlb_misses.stlb_hit,\
itlb_misses.walk_active,\
itlb_misses.walk_completed,\
itlb_misses.walk_completed_1g,\
itlb_misses.walk_completed_2m_4m,\
itlb_misses.walk_completed_4k,\
itlb_misses.walk_pending,\
cycles $1