perf stat -e \
offcore_response.demand_data_rd.any_response,\
offcore_response.demand_data_rd.l3_hit.any_snoop,\
offcore_response.demand_data_rd.l3_hit.snoop_hit_no_fwd,\
offcore_response.demand_data_rd.l3_hit.snoop_hitm,\
offcore_response.demand_data_rd.l3_hit.snoop_miss,\
offcore_response.demand_data_rd.l3_hit.snoop_none,\
offcore_response.demand_data_rd.l3_hit.snoop_not_needed,\
offcore_response.demand_data_rd.l3_hit.spl_hit,\
offcore_response.demand_data_rd.l3_hit_e.any_snoop,\
offcore_response.demand_data_rd.l3_hit_e.snoop_hit_no_fwd,\
offcore_response.demand_data_rd.l3_hit_e.snoop_hitm,\
offcore_response.demand_data_rd.l3_hit_e.snoop_miss,\
offcore_response.demand_data_rd.l3_hit_e.snoop_none,\
offcore_response.demand_data_rd.l3_hit_e.snoop_not_needed,\
offcore_response.demand_data_rd.l3_hit_e.spl_hit,\
offcore_response.demand_data_rd.l3_hit_m.any_snoop,\
offcore_response.demand_data_rd.l3_hit_m.snoop_hit_no_fwd,\
offcore_response.demand_data_rd.l3_hit_m.snoop_hitm,\
offcore_response.demand_data_rd.l3_hit_m.snoop_miss,\
offcore_response.demand_data_rd.l3_hit_m.snoop_none,\
offcore_response.demand_data_rd.l3_hit_m.snoop_not_needed,\
offcore_response.demand_data_rd.l3_hit_m.spl_hit,\
offcore_response.demand_data_rd.l3_hit_s.any_snoop,\
offcore_response.demand_data_rd.l3_hit_s.snoop_hit_no_fwd,\
offcore_response.demand_data_rd.l3_hit_s.snoop_hitm,\
offcore_response.demand_data_rd.l3_hit_s.snoop_miss,\
offcore_response.demand_data_rd.l3_hit_s.snoop_none,\
offcore_response.demand_data_rd.l3_hit_s.snoop_not_needed,\
offcore_response.demand_data_rd.l3_hit_s.spl_hit,\
offcore_response.demand_rfo.any_response,\
offcore_response.demand_rfo.l3_hit.any_snoop,\
offcore_response.demand_rfo.l3_hit.snoop_hit_no_fwd,\
offcore_response.demand_rfo.l3_hit.snoop_hitm,\
offcore_response.demand_rfo.l3_hit.snoop_miss,\
offcore_response.demand_rfo.l3_hit.snoop_none,\
offcore_response.demand_rfo.l3_hit.snoop_not_needed,\
offcore_response.demand_rfo.l3_hit.spl_hit,\
offcore_response.demand_rfo.l3_hit_e.any_snoop,\
offcore_response.demand_rfo.l3_hit_e.snoop_hit_no_fwd,\
offcore_response.demand_rfo.l3_hit_e.snoop_hitm,\
offcore_response.demand_rfo.l3_hit_e.snoop_miss,\
offcore_response.demand_rfo.l3_hit_e.snoop_none,\
offcore_response.demand_rfo.l3_hit_e.snoop_not_needed,\
offcore_response.demand_rfo.l3_hit_e.spl_hit,\
offcore_response.demand_rfo.l3_hit_m.any_snoop,\
offcore_response.demand_rfo.l3_hit_m.snoop_hit_no_fwd,\
offcore_response.demand_rfo.l3_hit_m.snoop_hitm,\
offcore_response.demand_rfo.l3_hit_m.snoop_miss,\
offcore_response.demand_rfo.l3_hit_m.snoop_none,\
offcore_response.demand_rfo.l3_hit_m.snoop_not_needed,\
offcore_response.demand_rfo.l3_hit_m.spl_hit,\
offcore_response.demand_rfo.l3_hit_s.any_snoop,\
offcore_response.demand_rfo.l3_hit_s.snoop_hit_no_fwd,\
offcore_response.demand_rfo.l3_hit_s.snoop_hitm,\
offcore_response.demand_rfo.l3_hit_s.snoop_miss,\
offcore_response.demand_rfo.l3_hit_s.snoop_none,\
offcore_response.demand_rfo.l3_hit_s.snoop_not_needed,\
offcore_response.demand_rfo.l3_hit_s.spl_hit,\
offcore_response.other.l3_hit.any_snoop,\
offcore_response.other.l3_hit.snoop_hit_no_fwd,\
offcore_response.other.l3_hit.snoop_hitm,\
offcore_response.other.l3_hit.snoop_miss,\
offcore_response.other.l3_hit.snoop_none,\
offcore_response.other.l3_hit.snoop_not_needed,\
offcore_response.other.l3_hit.spl_hit,\
offcore_response.other.l3_hit_e.any_snoop,\
offcore_response.other.l3_hit_e.snoop_hit_no_fwd,\
offcore_response.other.l3_hit_e.snoop_hitm,\
offcore_response.other.l3_hit_e.snoop_miss,\
offcore_response.other.l3_hit_e.snoop_none,\
offcore_response.other.l3_hit_e.snoop_not_needed,\
offcore_response.other.l3_hit_e.spl_hit,\
offcore_response.other.l3_hit_m.any_snoop,\
offcore_response.other.l3_hit_m.snoop_hit_no_fwd,\
offcore_response.other.l3_hit_m.snoop_hitm,\
offcore_response.other.l3_hit_m.snoop_miss,\
offcore_response.other.l3_hit_m.snoop_none,\
offcore_response.other.l3_hit_m.snoop_not_needed,\
offcore_response.other.l3_hit_m.spl_hit,\
offcore_response.other.l3_hit_s.any_snoop,\
offcore_response.other.l3_hit_s.snoop_hit_no_fwd,\
offcore_response.other.l3_hit_s.snoop_hitm,\
offcore_response.other.l3_hit_s.snoop_miss,\
offcore_response.other.l3_hit_s.snoop_none,\
offcore_response.other.l3_hit_s.snoop_not_needed,\
offcore_response.other.l3_hit_s.spl_hit,\
offcore_response.demand_rfo.l3_hit.snoop_non_dram,\
offcore_response.demand_rfo.l3_hit_e.snoop_non_dram,\
offcore_response.demand_rfo.l3_hit_m.snoop_non_dram,\
offcore_response.demand_rfo.l3_hit_s.snoop_non_dram,\
offcore_response.demand_rfo.l3_miss.any_snoop,\
offcore_response.demand_rfo.l3_miss.snoop_hit_no_fwd,\
offcore_response.demand_rfo.l3_miss.snoop_hitm,\
offcore_response.demand_rfo.l3_miss.snoop_miss,\
offcore_response.demand_rfo.l3_miss.snoop_non_dram,\
offcore_response.demand_rfo.l3_miss.snoop_none,\
offcore_response.demand_rfo.l3_miss.snoop_not_needed,\
offcore_response.demand_rfo.l3_miss.spl_hit,\
offcore_response.demand_rfo.l3_miss_local_dram.any_snoop,\
offcore_response.demand_rfo.l3_miss_local_dram.snoop_hit_no_fwd,\
offcore_response.demand_rfo.l3_miss_local_dram.snoop_hitm,\
offcore_response.demand_rfo.l3_miss_local_dram.snoop_miss,\
offcore_response.demand_rfo.l3_miss_local_dram.snoop_non_dram,\
offcore_response.demand_rfo.l3_miss_local_dram.snoop_none,\
offcore_response.demand_rfo.l3_miss_local_dram.snoop_not_needed,\
offcore_response.demand_rfo.l3_miss_local_dram.spl_hit,\
offcore_response.other.l3_hit.snoop_non_dram,\
offcore_response.other.l3_hit_e.snoop_non_dram,\
offcore_response.other.l3_hit_m.snoop_non_dram,\
offcore_response.other.l3_hit_s.snoop_non_dram,\
offcore_response.other.l3_miss.any_snoop,\
offcore_response.other.l3_miss.snoop_hit_no_fwd,\
offcore_response.other.l3_miss.snoop_hitm,\
offcore_response.other.l3_miss.snoop_miss,\
offcore_response.other.l3_miss.snoop_non_dram,\
offcore_response.other.l3_miss.snoop_none,\
offcore_response.other.l3_miss.snoop_not_needed,\
offcore_response.other.l3_miss.spl_hit,\
offcore_response.other.l3_miss_local_dram.any_snoop,\
offcore_response.other.l3_miss_local_dram.snoop_hit_no_fwd,\
offcore_response.other.l3_miss_local_dram.snoop_hitm,\
offcore_response.other.l3_miss_local_dram.snoop_miss,\
offcore_response.other.l3_miss_local_dram.snoop_non_dram,\
offcore_response.other.l3_miss_local_dram.snoop_none,\
offcore_response.other.l3_miss_local_dram.snoop_not_needed,\
offcore_response.other.l3_miss_local_dram.spl_hit,\
cycles $1