perf stat -e \
L1-dcache-load-misses,mem_load_retired.l1_miss,mem_load_retired.fb_hit,L1-dcache-loads,L1-dcache-stores,l1d.replacement,\
l1d_pend_miss.fb_full,l1d_pend_miss.pending,l1d_pend_miss.pending_cycles,\
l1d_pend_miss.pending_cycles_any,\
dTLB-load-misses,dTLB-loads,dTLB-store-misses,dTLB-stores,\
l2_lines_in.all,l2_lines_out.non_silent,l2_lines_out.silent,l2_lines_out.useless_hwpf,\
l2_rqsts.all_demand_data_rd,l2_rqsts.demand_data_rd_hit,l2_rqsts.demand_data_rd_miss,l2_rqsts.all_demand_miss,l2_rqsts.all_demand_references,\
l2_rqsts.all_pf,l2_rqsts.pf_hit,l2_rqsts.pf_miss,l2_rqsts.all_rfo,l2_rqsts.rfo_hit,l2_rqsts.rfo_miss,\
l2_rqsts.miss,l2_rqsts.references,\
l2_trans.l2_wb,\
LLC-loads,LLC-load-misses,LLC-stores,\
offcore_response.demand_data_rd.any_response,\
offcore_response.demand_rfo.any_response,\
offcore_response.other.any_response,\
offcore_requests.all_data_rd,\
offcore_requests.all_requests,\
offcore_requests.demand_data_rd,\
offcore_requests.demand_rfo,\
offcore_requests_buffer.sq_full,\
offcore_requests_outstanding.all_data_rd,\
offcore_requests_outstanding.cycles_with_data_rd,\
offcore_requests_outstanding.cycles_with_demand_data_rd,\
offcore_requests_outstanding.cycles_with_demand_rfo,\
offcore_requests_outstanding.demand_data_rd,\
offcore_requests_outstanding.demand_data_rd_ge_6,\
offcore_requests_outstanding.demand_rfo,\
offcore_response,\
bus-cycles,\
resource_stalls.any,resource_stalls.sb,r02a2,r04a2,r08a2,r10a2,r20a2,r40a2,r80a2,\
r0c5b,r0f5b,r405b,r4f5b,\
cycle_activity.cycles_mem_any,cycle_activity.cycles_l1d_miss,cycle_activity.cycles_l2_miss,cycle_activity.cycles_l3_miss,\
cycle_activity.stalls_mem_any,cycle_activity.stalls_l1d_miss,cycle_activity.stalls_l2_miss,cycle_activity.stalls_l3_miss,\
mem_trans_retired.load_latency_gt_4,mem_trans_retired.load_latency_gt_8,mem_trans_retired.load_latency_gt_16,\
mem_trans_retired.load_latency_gt_32,mem_trans_retired.load_latency_gt_64,mem_trans_retired.load_latency_gt_128,\
mem_trans_retired.load_latency_gt_256,mem_trans_retired.load_latency_gt_512,\
uops_retired.stall_cycles,uops_executed.stall_cycles,uops_issued.stall_cycles,\
cycle_activity.stalls_l1d_miss,cycle_activity.stalls_l2_miss,cycle_activity.stalls_l3_miss,\
cycle_activity.stalls_mem_any,cycle_activity.stalls_total,\
ld_blocks_partial.address_alias,ld_blocks.store_forward,ld_blocks.no_sr,\
cycles $1